// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2020-02-04T19:14:27.784Z

interface IAWSAmplifyFederatedConfiguration {
    google_client_id?: string;
    facebook_app_id?: string;
    amazon_client_id?: string;
}

interface IAWSAmplifyCloudLogicConfiguration {
    [index: number]: {
        endpoint: string;
        name: string;
        region: string;
    };
}

interface IAWSAmplifyConfiguration {
    aws_appsync_authenticationType?: string;
    aws_appsync_graphqlEndpoint?: string;
    aws_appsync_region?: string;
    aws_cognito_identity_pool_id?: string;
    aws_cognito_region?: string;
    aws_cloud_logic_custom?: IAWSAmplifyCloudLogicConfiguration;
    aws_project_region: string;
    aws_user_files_s3_bucket?: string;
    aws_user_files_s3_bucket_region?: string;
    aws_user_pools_id?: string;
    aws_user_pools_web_client_id?: string;
    aws_user_pools_web_client_secret?: string;
    federated?: IAWSAmplifyFederatedConfiguration;
}

const awsmobile: IAWSAmplifyConfiguration = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://9eewuz2n2h.execute-api.ap-south-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'ap-south-1'
        }
    ],
    aws_cognito_identity_pool_id: 'ap-south-1:cf471a98-ecc8-47d0-bf87-fbb670c30cff',
    aws_cognito_region: 'ap-south-1',
    aws_project_region: 'ap-south-1',
    aws_user_files_s3_bucket: 'n6lb-dev-resources',
    aws_user_files_s3_bucket_region: 'ap-south-1',
    aws_user_pools_id: 'ap-south-1_jKrUvXR3i',
    aws_user_pools_web_client_id: '1ul9hqi883ilcb5c60l1e9r74k'
};

export default awsmobile;
