
service: n6lb # نطلب

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-plugin-typescript
#  - serverless-iot-local
  - serverless-offline
  - serverless-plugin-log-retention
  - aws-amplify-serverless-plugin



provider:
  name: aws
  runtime: nodejs10.x
  stage:  ${opt:stage, 'dev'}
  region: ${file(./env.yaml):${self:provider.stage}.REGION}
  versionFunctions: false
  cfnRole: redacted

  environment:
    ${file(./env.yaml):${self:provider.stage}}


functions:
  graphql:
    handler: src/graphql/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true


resources:
   - ${file(resources/s3.yml)}
   - ${file(resources/cognito.yml)}
   - ${file(resources/iot.yml)}


custom:
  amplify:
    - filename: ./aws-exports.ts
      type: typescript
#  serverless-iot-local:
#    start:
#      port: 1884
#    # Uncomment only if you already have an MQTT server running locally
#    # noStart: true
#    redis:
#      host: 'localhost'
#      port: 6379
#      db: 12

  
