
service: n6lb # نطلب 

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-appsync-plugin
  - serverless-appsync-offline
  - serverless-offline
  - serverless-plugin-log-retention
  - aws-amplify-serverless-plugin


provider:
  name: aws
  runtime: nodejs10.x
  region: ap-south-1
  stage: dev
  versionFunctions: false
  cfnRole: redacted

  environment:
    COMPANIES_TABLE: ${self:service}-${self:provider.stage}-companies
    BRANCHES_TABLE: ${self:service}-${self:provider.stage}-branches
    TABLES_TABLE: ${self:service}-${self:provider.stage}-tables
  
  iamRoleStatements:
   - Effect: Allow
     Action: 
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
     Resource:
      - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLES_TABLE}

functions:
  addTable:
    handler: src/preSignup.addCompany
    events: 
      - http:
          path: add_table
          method: post
          cors: true

resources:
  - ${file(resources/dynamo.yml)}
  # - ${file(resources/s3.yml)}
  # - ${file(resources/cognito.yml)}

custom:
  dynamodb:
    stages:
      - dev
  appSync:
    - ${file(resources/appsync.yml)}
  appsync-offline: # appsync-offline configuration
    port: 62222
    # schema: src/graphql/schema.gql
    dynamodb:
      client:
        endpoint: "http://localhost:8000"
  
