name:  ${self:service}-console-${self:provider.stage}
authenticationType: AMAZON_COGNITO_USER_POOLS
# if AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  defaultAction: ALLOW
  userPoolId: { Ref: CognitoUserPoolINeedPool }
  playgroundClientId: { Ref: CognitoUserPoolClient }

logConfig:
  loggingRoleArn: "redacted"
  level: ERROR # Logging Level: NONE | ERROR | ALL
mappingTemplatesLocation: src/graphql/mapping-templates
schema: src/graphql/schema.gql
dataSources:
  - type: NONE
    name: NoneDS

  - type: HTTP
    name: RocksetDS
    description: 'Rockset Endpoint'
    config:
      endpoint: 'https://api.rs2.usw2.rockset.com/'

  
  - type: AMAZON_DYNAMODB
    name: DynamoBranchesTableDS
    description: 'DynamoDB Branches Table'
    config:
      tableName: { Ref: branchesTable } 
      iamRoleStatements: 
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.BRANCHES_TABLE}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.BRANCHES_TABLE}/index/*"
  
substitutions: # allows to pass variables from here to velocity templates
  # ${stage} will be replaced with given value in all mapping templates
  stage: "${self:provider.stage}"

mappingTemplates:

  - dataSource: DynamoBranchesTableDS
    type: Query 
    field: getCompany
    request: Common.query.request.vtl
    response: Common.query.response.vtl