Resources:
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      BucketName: ${self:provider.environment.S3BUCKET}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

  AttachementBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: AttachmentsBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:PutObjectAcl
              - s3:GetBucketLocation
              - s3:ListBucket

            Effect: Allow
            Resource:
              - Fn::Join:
                  - ''
                  - - Fn::GetAtt: [AttachmentsBucket, Arn]
                    - '/*'
              - Fn::GetAtt: [AttachmentsBucket, Arn]
            Principal:
              AWS:
                - Fn::GetAtt: [CognitoAuthRole, Arn]
                - Fn::GetAtt: [IamRoleLambdaExecution, Arn]

Outputs:
  AttachmentsBucketName:
    Value:
      Ref: AttachmentsBucket
