type Company {
	id: String!
	email: String!
	logo: String
	call_center: String
	english_name: String!
	arabic_name: String!
	added_date: String!
	status: String!
	subscription: String!
	documents: [Document!]
	branches: [Branch]!
	cars: [Car]
	employees: [Employee]
	customers: [Customer]
	reservations: [Reservation]
	statistics: Statistics
}

input DeliveryInput {
	available: Boolean!
	fixed_price: Float!
	km_price: Float!
	hours: [HoursInput!]
	max_distance: Float!
	allow_unverified: Boolean!
	confirmation_required: Boolean!
	num_of_drivers: Int!
}


# ============= Root Types ============= #
type Mutation {
	deleteCar(id: String!, company_id: String!): String!
}

type Query {
	getCompany(id: String!): Company
	getBranch(id: String!, company_id: String!): Branch!
}

type Subscription {
	onAddReservation(company_id: String!): Reservation @aws_subscribe(mutations: ["addReservation"])
}

schema {
    query: Query
    mutation: Mutation
	subscription: Subscription
}
